web:
  image: golang:1.8
  working_dir: /go/src/app
  command: go run main.go
  volumes:
    - ${SHED_PATH}:/go/src/app
  expose:
    - 80
  restart: always
  environment:
    - VIRTUAL_HOST=${SHED_HOST}